spring:
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#    username: &username ${DB_CONNECTION_USERNAME:root}
#    password: &password ${DB_CONNECTION_PASSWORD:root}
  jpa:
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false

#  kafka:
#    bootstrap-servers: kafka:9092

  cloud:
    function:
      definition: clients-register
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        clients-register-out-0:
          destination: clients-register
          group: clients-ms-group
          contentType: application/json


server:
  port: 8080
springdoc:
    paths-to-exclude: /failed-clients